<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.1.4</Version>
    <AssemblyVersion>1.1.4.0</AssemblyVersion>
    <FileVersion>1.1.4.0</FileVersion>
    <InformationalVersion>1.1.4</InformationalVersion>
  </PropertyGroup>

</Project>
