<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>ABBRelaysAuthorizationTool</AssemblyName>
    <ApplicationIcon>Assets\abb-relays-auth.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="$(MaterialDesignThemesVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbbRelaysLicensing\AbbRelaysLicensing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\abb-relays-auth.ico" />
  </ItemGroup>

</Project>
