<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>REX615AuthorizationTool</AssemblyName>
    <Version>1.1.4</Version>
    <AssemblyVersion>1.1.4.0</AssemblyVersion>
    <FileVersion>1.1.4.0</FileVersion>
    <InformationalVersion>1.1.4</InformationalVersion>
    <ApplicationIcon>Assets\rex615-auth.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rex615Licensing\Rex615Licensing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\rex615-auth.ico" />
  </ItemGroup>

</Project>
